#System setup
ARDUINO_DIR=/usr/share/arduino
MONITOR_PORT=/dev/ttyACM*
AVRDUDE=/usr/bin/avrdude
AVRDUDE_CONF=/etc/avrdude.conf

#Sketch setup
BOARD_TAG=uno
USER_LIB_PATH=/home/alvenan/Documents/arduino/libraries

ARDUINO_LIBS=NewLiquidCrystal
ARDUINO_LIBS+=Wire
ARDUINO_LIBS+=Servo

include /usr/share/arduino/Arduino.mk


